### ISSUE TITLE
Menu da mini.css

### ISSUE THREAD

**Issue by PericMarko01** [ArteAccessibile/Progetto#2]
La pagina selezionata nel menù non ha la stessa distanza dal lato, e con padding non cambia se a qualcuno interessa risolverlo io non sono riuscito
![Immagine 2023-12-13 173349](https://github.com/ArteAccessibile/Progetto/assets/126680977/f0c99fee-0c85-4124-b2dd-7520af18262b)

**Comment by Fgiacomuzzo** [comment]
oggi abbiamo provato a fare un menu ad hamburgher, funziona, ma poi non si vede nulla nella galleria. Ora sto smattando di nuovo per farlo funzionare da tutte e due le parti

**Comment by Fgiacomuzzo** [comment]
![Screenshot 2023-12-13 184257](https://github.com/ArteAccessibile/Progetto/assets/124695588/52e7db93-9651-46fe-9b17-fbc3eb42a603)
esempio se cliccato:


![image](https://github.com/ArteAccessibile/Progetto/assets/124695588/e1b29cfb-9626-4be5-a06f-da9d6e2e54b8)

**Comment by PericMarko01** [comment]
Sempre per il mini questo?
In caso non potremmo coprire tutto con il menu quando viene aperto?

**Comment by Fgiacomuzzo** [comment]
creato il menu css, intanto solo per la galleria
